### ISSUE TITLE
Specify webcam device for macOS

### ISSUE THREAD

**Issue by aksharabruno** [NeelBhowmik/efficient-compact-fire-detection-cnn#2]
What is the parameter value to be given to make use of a webcam after '--camera_to_use'?

**Comment by NeelBhowmik** [comment]
Hi,
Default value of '--camera_to_use' is 0. Usually, that is the default camera index or when you add a USB camera, it will be indexed from '_0_' to '_n_', where _n = 1,2,3..._(on Ubuntu - the code is tested on Ubuntu). I assume it will be similar for MacOS. Thanks.
