### ISSUE TITLE
Training with another dataset

### ISSUE THREAD

**Issue by YasmineHamdy** [NeelBhowmik/efficient-compact-fire-detection-cnn#3]
Thank you for sharing the code,
we are interested in your paper and want to build the model using another dataset.
So, Could you please share the training scripts ?

**Comment by NeelBhowmik** [comment]
Hi,
Usually, we don't provide a training script. However, the two proposed models (nasnet-onfire/shufflenet-onfire) are present in _'models/'_ directory, and you can use these codes to create a training script.

Thanks.
