### ISSUE TITLE
Could I know how to train?

### ISSUE THREAD

**Issue by JoonHoonKim** [NeelBhowmik/efficient-compact-fire-detection-cnn#4]
I want to use this model for fire detection. I have own custom datasets. Could I know how to train??
Thank you!

**Comment by NeelBhowmik** [comment]
Hi,
Usually, we don't provide a training script. However, the two proposed models (_nasnet-onfire/shufflenet-onfire_) are present in _'models/_' directory, and you can use these codes to create a training script.

Thanks.

**Comment by JoonHoonKim** [comment]
> 

Thank you for the reply! 
I have some questions. 

1. Are the images in the isolated directory in the dataset a patch image(superpixel image)?

2. If it is a patch image, did you train the patch image(superpixel image) as the Classifier?

Thank you!

**Comment by HaQuocHuyPtit** [comment]
Đọc báo đi em

**Comment by NeelBhowmik** [comment]
Hi,
Apology for the late reply. Please let me know if you still need help on this.

Thanks,
Neel

**Comment by JoonHoonKim** [comment]
> Hi, Apology for the late reply. Please let me know if you still need help on this.
> 
> Thanks, Neel

I have solved my questions. Thank you for reply. :)
