### ISSUE TITLE
Model does not work properly, error cannot initialize QT

### ISSUE THREAD

**Issue by qianfulin** [NeelBhowmik/efficient-compact-fire-detection-cnn#5]
FactoryLoader::QFactoryLoader() checking directory path "/efficient-compact-fire-detection-cnn-main/venv/lib/python3.6/site-packages/cv2/qt/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/efficient-compact-fire-detection-cnn-main/venv/lib/python3.6/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
Found metadata in lib /efficient-compact-fire-detection-cnn-main/venv/lib/python3.6/site-packages/cv2/qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
loaded library "/efficient-compact-fire-detection-cnn-main/venv/lib/python3.6/site-packages/cv2/qt/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/efficient-compact-fire-detection-cnn-main/venv/lib/python3.6/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)

**Comment by qianfulin** [comment]
OS：jetpack 4.4

**Comment by NeelBhowmik** [comment]
Hi,
At this point, I am not sure about the error you are encountering. 
This code was not tested on QT platform yet.

Thanks,
